// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjnfgpndpydcbgrlrpmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbmZncG5kcHlkY2JncmxycG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTM3ODksImV4cCI6MjA1OTc2OTc4OX0.vSWdLmYksvg8RyE7aoi-HaoVgAwMqcKQ4SJKpt27pFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);